### ISSUE TITLE
_sqlite3.so: has text relocations

### ISSUE THREAD

**Issue by danielrosero** [ainsophical/DROID_PYTHON#10]
I'm trying to get Instabot running inside Android.
I managed to import all the dependencies successfully, but came to this issue with _sqlite3.

So far I have tried to replace sqlite3.so  with other compilations unsuccessfully.

Any change you can help?

Thanks for this project.

```
ux:/data/data/com.android.python27/files` # python example.py                                       
WARNING:` linker: Warning: unable to normalize ""

WARNING: linker: Warning: unable to normalize ""
WARNING: linker: Warning: unable to normalize ""
WARNING: linker: Warning: unable to normalize ""
WARNING: linker: Warning: unable to normalize ""
WARNING: linker: /data/data/com.android.python27/files/python/lib/python2.7/lib-dynload/_sqlite3.so: unused DT entry: type 0xf arg 0x1591
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/data/data/com.android.python27/files/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/data/data/com.android.python27/files/src/instabot.py", line 15, in <module>
    import sqlite3
  File "/data/data/com.android.python27/files/packages/python/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/data/data/com.android.python27/files/packages/python/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen failed: /data/data/com.android.python27/files/python/lib/python2.7/lib-dynload/_sqlite3.so: has text relocations
```

**Comment by michaelrinderle** [comment]
i've never used instabot but you can check : 

- what version of sqlite does instabot require
- is your updated sqlite3.so compiled with android ndk? the binary needs to be compiled for the arm arch.

**Comment by danielrosero** [comment]
Its the one that comes with the python_27.zip package.

**Comment by michaelrinderle** [comment]
okay, is there a constraint for a specific version of slqlite? is it using a specific orm? i've used sqlalchemy with sqlite & droid-python , but i can't confirm if I had to modify it at all.

**Comment by danielrosero** [comment]
I'm sorry, I don't understand what you are saying Michael. How do I check
it out?

What I did yesterday was to try out replacing the python_27.zip and
python27_extras.zip for pythonr33.zip and pythonr33_extras.zip

But still not working. Told me something of site package not found.

Thank you for helping me out Michael

**Comment by michaelrinderle** [comment]
NP. Yes, don't do that, just asking for more problems to figure out.  

When importing a python package that is not included you have to make sure you have not only the right dependencies but it has to be a pure python package. So you have to browse the code @ https://github.com/instagrambot/instabot to see if it doesn't depend on any c libraries that are not compiled to arm as well as if there is any requirements for a specific sqlite version. I don't recall off the top of my head which version is compiled and included in this repo.

**Comment by danielrosero** [comment]
I see. Forgot to tell you that yesterday I did put the Instabot project to
work, but unfortunately not with your droid_python project but directly
installing sl4a.apk and pythonforandroid.apk and then calling the example
script from the interpreter. The bot works without any problems this way,
so I guess there is no problem with C modules of any kind.

I hope you can help me to solve this sqlite3 issue, one thing that I love
of yours, is that the environment comes all packed up in the apk that
droid_python deploys, no need for third party apps.

**Comment by michaelrinderle** [comment]
No doubt. If you hybrid it into a webview / python backend server app, the performance is terrific on android. Ahh! Sorry, its been awhile; if you are deploying to an emulator, you need an ARM version, too. Unfortunately, I write all my apps in c#\xamarin so I have little interest in this project anymore.

Email me your email address and I'll pass you my current pymod & py27 zip files for you to try if you keep hitting a roadblock; michael@sofdigital.net
